### ISSUE TITLE
Broken rings effect on the Special Stage.

### ISSUE THREAD

**Issue by Storm3000** [lory90/ps4disasm-uncomp#1]
Hi, Iory90.

I don't know where to put this. Sorry  to bother you here.

In Sonic 2 Improvement hack, playing with Sonic and Tails, Tails alone or Sonic alone, when entering to Special Stage, the stars effect when Sonic collect the rings looks broken. It happens almost every time you enter a Special Stage. It doesn't happen on the original Sonic 2 Rev A version.

**Comment by lory90** [comment]
Hi.

No problem! Someone else pointed out this issue a couple of years ago....I don't know when I can find some time to look into this, but I will keep this in mind. However you mentioned that it happens all the time for you, while it only happened sporadically for me, and I couldn't find a way to make it consistent. What emulator are you using? Can you tell me the quickest route you take from the start of the game to a Special Stage for the bug to show up? I think I have a clue what's going on, but first I need to make sure I can replicate the bug and go from there.

**Comment by Storm3000** [comment]
I'm using MD.emu for Android, and Kega Fusion for PC. The bug happens on both emulators.

I tried on the first and second checkpoint of Emerald Hill Zone 1, but it happens in others zones too. It happens only when using Sonic and Tails, or Tails alone, but works fine if I only use Sonic. Maybe the problem has something to do with Tails. It doesn't happen always, but almost every time.

**Comment by Storm3000** [comment]
I'm using MD.emu for Android, and Kega Fusion for PC. The bug happens on both emulators.

I tried on the first and second checkpoint of Emerald Hill Zone 1, but it happens in others zones too. It happens only when using Sonic and Tails, or Tails alone, but works fine if I only use Sonic. Maybe the problem has something to do with Tails. It doesn't happen always, but almost every time.

**Comment by Storm3000** [comment]
My theories:

1. The bug could be related to the amount of rings collected before reach a checkpoint. Not sure about this.
2. The bug could happen if Sonic or Tails keeps collecting more rings after reach a checkpoint with 50 rings or more collected and the portal to Special Stage completely open. It seems the bug occurs more often when I do this.
3. The bug could be related to these changes on the hack considering these are the only changes related to Special Stages:
- Fixed buggy BCD converter for the ring requirement when you need 101 or more rings in Special Stages.
- Fixed freezing issue when entering the special stage using emulators other than
  Kega Fusion.

**Comment by Storm3000** [comment]
If you don't mind, could you pass me the source code of the original game related to those two bugfixes I mentioned before to restore it with a hex editor? I'd like to try if the bug is related to the freezing fix to Special Stages.

**Comment by lory90** [comment]
The bug was already reported before the BDC converted fix, so it can't be that. As for the emulator fix, that was in version 1.1 where there were slightly modified code; starting from v2.0, the entire original Special Stage code was restored.

I keep getting random results. I can enter a SS 10 times and not get it, while I run into the bug the next 2, 3 times. I can't find the cause just by playtesting. The stars when you get the rings is not the only glitch....even Tails name can get glitched and there's some wrong graphics even when the START wording shows up at the beginning of a SS. The graphics involved in this are in certain part of VRAM, so I need to look into what happens in that area and check the fixes regarding the graphics issues to see if one of them is the cause.

**Comment by lory90** [comment]
Oh wow. This is retarded. I started from a clean disassembly and there was some comments saying that something should've been removed. Of course I did apply it and I had the bug. 

Anyway I reimplemented the original code for that section....I tried a few times and the problem should be gone, but I want you to test as well, so we're safe. Get the new ROM from the following link:

[https://www.dropbox.com/s/ojuu05z90u9ummy/s2built.bin?dl=0](url)

**Comment by Storm3000** [comment]
It's working great now. Thank you so much. :)

This is an amazing hack, making the best version available for Sonic 1 and 2, in my opinion.

Are you planning to release a bugfix hack for Sonic 3 & Knuckles? That would be awesome.

**Comment by lory90** [comment]
Nice!

Well, Sonic 3&K is my favorite game and I would love to, but it has so many bugs it's a little overwhelming. I study the source code from time to time, and some bugs require further understanding. Also, I don't have much time right now, so...

Honestly I've always been reluctant to release a bugfix patch for that game since there's already Sonic 3 Complete which has many bugfixes and more, so a simple bugfix hack would be obsolete I think. But sometimes I still think about wanting to make it just for personal exercise; we'll see.

**Comment by Storm3000** [comment]
I tried to play the Sonic 3 Complete. It's a nice hack, but it looks too different to me compared to the original game. Looks like an alternate version to the original Sonic 3. I think it would be a great version if only had the bugfixes included.

I wanna ask you. What's the difference between the two .ips files included in the Sonic 1 Bugfix hack? I'm not sure which one should I use for the USA/European rom. I know one of them contains the changes from the Japanese version, but I don't know which one.

**Comment by lory90** [comment]
Yeah, I'm not a fan of Sonic 3 Complete either. I appreciate the effort, but the game is not the same to me.
I could start working on some fixes and release a patch, then I will update it with more stuff every so often....I think it would be more manageable that way.

Sonic_Bugfix_rev1.ips contains the bugfixes for the Japanese version. Make sure to still apply to the USA/EU version of the original game.

Do you have an email address? It would be better to talk that way. Mine is

lory2004@gmail.com

I will update github with my email info as well.

**Comment by Storm3000** [comment]
Thanks for the info. :)

I found another minor bug. At the end of Chemical Plant Zone 1, the mark with Sonic picture is floating a little. If you jump, you will notice.

My email is: adrian.ruarte@hotmail.com
